spring.application.name=ecomerce

spring.rabbitmq.username=admin
spring.rabbitmq.password=123456

# Habilita as tentativas
spring.rabbitmq.listener.simple.retry.enabled=true

# Número máximo de tentativas antes de rejeitar a mensagem
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Tempo de espera entre cada tentativa (1 segundo)
spring.rabbitmq.listener.simple.retry.initial-interval=1000


# Configurações do Servidor de Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucashenriquebarros2016@gmail.com
spring.mail.password=mmnywkuuonrodgon

# Propriedades de segurança exigidas pelo Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true